"""
Liu-Weinstein-Xu (LWX) Courant bracket on a triangular Lie bialgebroid.

For a triangular Lie bialgebroid ``(TM, T^*M)`` generated by a Poisson
bivector ``π`` (see :class:`~jacopy.library.triangular_lie_bialgebroid.TriangularLieBialgebroid`),
the LWX Courant bracket on section pairs of ``TM ⊕ T^*M`` is

    [(U, ω), (V, η)]_LWX
        = ( [U, V]_{TM} + L̃_ω V − L̃_η U − d̃ι̃_η U,
            [ω, η]_{T*M} + L_U η − L_V ω + d ι_V ω
            [+ ι_V ι_U H] ),

where the standard Cartan operators ``(d, L, ι)`` act on the form half
(TM-side data) and the tilde operators ``(d̃, L̃, ι̃)`` plus the
classical Koszul bracket ``[·,·]_{T*M}`` act on the vector half (T*M-side
data). The ``H``-twist (closed 3-form on the base) is optional and
contributes only to the form half, mirroring the standard Courant
construction.

This bracket is the **Stage F** triangular-bialgebroid generalisation
of the standard exact :class:`~jacopy.brackets.courant.CourantBracket`:
the latter is recovered as the special case ``π = 0`` (no Koszul,
no tilde-calculus, no T*M-side anchor; vector half collapses to
``[U, V]_{TM}`` and form half to ``L_U η − L_V ω − ½ d(ι_U η − ι_V ω)``,
modulo the inner-product convention used by the wrapper). For the
``π ≠ 0`` triangular case the LWX bracket is what Q3.1.6 actually
asks to verify the Courant algebroid axioms for; the standard
:class:`CourantBracket` is the π=0 dilim of that statement.

The form half of the LWX bracket is *Dorfman-style* (not graded
antisymmetric on its own); the antisymmetric Courant version is its
symmetrisation modulo the inner product, exactly the same relationship
the standard exact bracket has with its Dorfman twin.
"""

from __future__ import annotations

from typing import Any, Optional

from jacopy.algebra.derivation import Act
from jacopy.brackets.base import GradedBracket
from jacopy.brackets.derived import VanishingCondition
from jacopy.brackets.dorfman import SectionPair
from jacopy.core.expr import Expr, Neg, Sum
from jacopy.core.registry import PropertyRegistry


class LWXCourantBracket(GradedBracket):
    """LWX Courant bracket on ``TM ⊕ T*M`` for a triangular bialgebroid.

    Parameters
    ----------
    bialgebroid
        :class:`~jacopy.library.triangular_lie_bialgebroid.TriangularLieBialgebroid`
        carrying the Poisson bivector ``π`` and the induced T*M-side
        Koszul bracket + tilde-calculus operators.
    name
        Optional display name; defaults to ``"[·,·]_LWX"`` or its
        H-twisted variant.
    background_H
        Optional closed 3-form ``H`` on the base; when present the
        bracket gains the ``+ ι_V ι_U H`` form-half twist.

    Notes
    -----
    * Degree 0; the bracket is *not* graded antisymmetric in this
      Dorfman-style form (its symmetrisation is the antisymmetric
      Courant cousin, off by an inner-product correction). The flag
      :attr:`is_graded_antisymmetric` is set to ``False`` so the
      proof layer doesn't try to apply skew-symmetric rewrite rules
      to the bracket itself.
    * Leibniz holds (Vaisman form, with the inner-product correction
      term coming from the LWX construction); the flag
      :attr:`satisfies_leibniz` is set to ``True``.
    * Jacobi is conditional: holds untwisted, requires ``dH = 0`` for
      the H-twisted version. The flag is ``None``, matching the
      :class:`~jacopy.brackets.courant.CourantBracket` convention.
    """

    def __init__(
        self,
        bialgebroid: Any,
        name: Optional[str] = None,
        *,
        background_H: Optional[Expr] = None,
    ) -> None:
        # Avoid a hard import-time dependency on the library wrapper:
        # late-bind the type check via duck-typing on the attributes
        # we actually consume below. This keeps the brackets package
        # free of any import on jacopy.library.
        for attr in (
            "tm_bracket", "tm_d", "tm_lie_derivative", "tm_interior",
            "koszul", "tilde_d", "tilde_lie_derivative", "tilde_interior",
            "sharp", "pi",
        ):
            if not hasattr(bialgebroid, attr):
                raise TypeError(
                    f"LWXCourantBracket bialgebroid is missing attribute "
                    f"'{attr}'; expected a TriangularLieBialgebroid"
                )
        if background_H is not None and not isinstance(background_H, Expr):
            raise TypeError(
                "LWXCourantBracket background_H must be an Expr when given"
            )
        if name is None:
            name = (
                "[·,·]_LWX"
                if background_H is None
                else f"[·,·]_LWX,H={background_H._repr_inner()}"
            )
        super().__init__(
            name,
            degree=0,
            is_graded_antisymmetric=False,
            satisfies_leibniz=True,
            satisfies_graded_jacobi=None,
        )
        self._bialgebroid = bialgebroid
        self._background_H = background_H

    # ---- accessors -------------------------------------------------- #

    @property
    def bialgebroid(self) -> Any:
        return self._bialgebroid

    @property
    def background_H(self) -> Optional[Expr]:
        return self._background_H

    @property
    def is_twisted(self) -> bool:
        return self._background_H is not None

    # ---- expansion -------------------------------------------------- #

    def expand(
        self,
        a: Expr,
        b: Expr,
        registry: Optional[PropertyRegistry] = None,
    ) -> Expr:
        """LWX Courant bracket on :class:`SectionPair` operands.

        Vector half: ``[U, V]_{TM} + L̃_ω V − L̃_η U − d̃ι̃_η U``.
        Form half: ``[ω, η]_{T*M} + L_U η − L_V ω + d ι_V ω`` plus
        the optional ``+ ι_V ι_U H`` twist contribution.
        """
        if not isinstance(a, SectionPair):
            raise TypeError(
                f"LWXCourantBracket left operand must be a SectionPair, "
                f"got {type(a).__name__}"
            )
        if not isinstance(b, SectionPair):
            raise TypeError(
                f"LWXCourantBracket right operand must be a SectionPair, "
                f"got {type(b).__name__}"
            )
        U, omega = a.vector, a.form
        V, eta = b.vector, b.form

        TLB = self._bialgebroid

        # ---- vector half --------------------------------------- #
        # [U, V]_TM (canonical)
        vec_lie = TLB.tm_bracket.expand(U, V, registry)
        # L̃_ω V (T*M-side Lie derivative of ω acting on V)
        L_tilde_omega = TLB.tilde_lie_derivative(omega)
        L_tilde_eta = TLB.tilde_lie_derivative(eta)
        iota_tilde_eta = TLB.tilde_interior(eta)
        d_tilde = TLB.tilde_d
        # − L̃_η U
        # − d̃ι̃_η U
        vector_terms = [
            vec_lie,
            Act(L_tilde_omega, V),
            Neg(Act(L_tilde_eta, U)),
            Neg(Act(d_tilde, Act(iota_tilde_eta, U))),
        ]
        vector_part = Sum(*vector_terms)

        # ---- form half ----------------------------------------- #
        # [ω, η]_{T*M}
        form_koszul = TLB.koszul.expand(omega, eta, registry)
        # L_U η, L_V ω, d ι_V ω
        L_U = TLB.tm_lie_derivative(U)
        L_V = TLB.tm_lie_derivative(V)
        iota_V = TLB.tm_interior(V)
        iota_U = TLB.tm_interior(U)
        d_op = TLB.tm_d
        form_terms = [
            form_koszul,
            Act(L_U, eta),
            Neg(Act(L_V, omega)),
            Act(d_op, Act(iota_V, omega)),
        ]

        # H-twist contribution: + ι_V ι_U H (form half).
        if self._background_H is not None:
            form_terms.append(
                Act(iota_V, Act(iota_U, self._background_H))
            )

        form_part = Sum(*form_terms)
        return SectionPair(vector_part, form_part)

    # ---- Jacobi condition ------------------------------------------ #

    def jacobi_condition(
        self,
        registry: Optional[PropertyRegistry] = None,
    ) -> VanishingCondition:
        """Return the :class:`VanishingCondition` for LWX Jacobi.

        Mirrors :meth:`~jacopy.brackets.courant.CourantBracket.jacobi_condition`:

        * **Untwisted** (``background_H is None``): obstruction is
          :class:`Zero`-valued. The cyclic Jacobiator collapses by the
          full LWX compatibility identities (``[π, π]_SN = 0`` provides
          the Koszul-side Jacobi; the cross identities provide mixed
          cancellation; the standard Lie bracket on TM provides the
          remaining piece).
        * **H-twisted**: obstruction is ``dH``. Same closure condition
          as the standard exact Courant — ``dH = 0`` discharges the
          Jacobi obstruction.
        """
        if self._background_H is None:
            from jacopy.core.expr import Zero
            return VanishingCondition(
                obstruction=Zero,
                name="LWX Courant Jacobi (untwisted, vacuous)",
            )
        d_op = self._bialgebroid.tm_d
        return VanishingCondition(
            obstruction=Act(d_op, self._background_H),
            name=(
                f"LWX Courant Jacobi condition "
                f"(H-twisted by {self._background_H._repr_inner()})"
            ),
        )

    # ---- identity -------------------------------------------------- #

    def _identity_key(self) -> Any:
        return super()._identity_key() + (
            id(self._bialgebroid),
            self._background_H,
        )
